### ISSUE TITLE
検査実施数のポップアップに「都内」表記がある

### ISSUE THREAD

**Issue by nishimotz** [tatsuya1970/covid19#3]
## 起こっている問題 / The Problem

検査実施数のポップアップに「都内」表記がある

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/76300/77021957-9d815d80-69cb-11ea-88ba-a558750e1553.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「県内」だと思われる

## 起こっている問題の再現手段 / Steps to Reproduce

1. Windows Chrome でサイトを開く
2. 検査実施数の縦棒グラフのどれかにマウスポインタを合わせる
3. 黒背景のポップアップに「都内」と書かれている

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

**Comment by tatsuya1970** [comment]
ありがとうございます！
修正しました！

/components/TimeStackedBarChart.vue
143行目
const labelTokyo = this.$t(‘都内) 　＝＞　const labelTokyo = this.$t('県内')
